server:
  port: ${PORT:0}
spring:
  cloud:
    config:
      uri: http://config-service:8888
  profiles:
    active: dev
  application:
    name: ms-pedido
management:
  endpoints:
    web:
      exposure:
        include:
        - '*'
eureka:
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
